const dataset = [
  { language: "pt", text: "e aeeeee", definition: "GREET" },
  { language: "pt", text: "eae", definition: "GREET" },
  { language: "pt", text: "e ae", definition: "GREET" },
  { language: "pt", text: "oiii", definition: "GREET" },
  { language: "pt", text: "oi", definition: "GREET" },
  { language: "pt", text: "ola", definition: "GREET" },
  { language: "pt", text: "olá", definition: "GREET" },
  { language: "pt", text: "tudo bem", definition: "GREET" },
  { language: "pt", text: "tudobem", definition: "GREET" },
  { language: "pt", text: "como vai voce", definition: "GREET" },
  { language: "pt", text: "e ae, tudo bem", definition: "GREET" },
  { language: "pt", text: "bom dia", definition: "GREET" },
  { language: "pt", text: "boa tarde", definition: "GREET" },
  { language: "pt", text: "boa noite", definition: "GREET" },
  { language: "pt", text: "tudo certo", definition: "GREET" },
  { language: "pt", text: "onde fica", definition: "LOCATION" },
  { language: "pt", text: "como posso encontrar", definition: "LOCATION" },
  { language: "pt", text: "localizacao", definition: "LOCATION" },
  { language: "pt", text: "localização", definition: "LOCATION" },
  { language: "pt", text: "quais lojas", definition: "LOCATION" },
  { language: "pt", text: "tchau", definition: "ENDING" },
  { language: "pt", text: "muito obrigado", definition: "ENDING" },
  { language: "pt", text: "até logo", definition: "ENDING" },
  { language: "pt", text: "até", definition: "ENDING" },
  { language: "pt", text: "ate", definition: "ENDING" },
  { language: "pt", text: "ate logo", definition: "ENDING" },
  { language: "pt", text: "valeu", definition: "ENDING" },
  { language: "pt", text: "vlw", definition: "ENDING" },
  { language: "pt", text: "vlwwww", definition: "ENDING" },
  { language: "pt", text: "vlww", definition: "ENDING" },
  { language: "pt", text: "vlwww", definition: "ENDING" },
];

export { dataset };
